channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=22.0.4
- pip:
  - mlflow==2.7.1
  - argparse==1.4.0
  - cloudpickle==2.2.1
  - numpy==1.19.5
  - packaging==22.0
  - psutil==5.9.6
  - pyyaml==6.0
  - scikit-learn==0.24.2
  - scipy==1.11.3
name: mlflow-env
